In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import toponetx
from toponetx.transform.graph_to_simplicial_complex import graph_to_neighbor_complex
from topobenchmarkx.data.liftings.liftings import SimplicialNeighborhoodLifting, CellCyclesLifting
import networkx as nx

In [5]:
g = nx.Graph()
g.add_nodes_from([1,2,3,4,5,6])
g.add_edges_from([(1,2),(1,3),(1,4),(2,3),(2,4),(2,5),(3,4),(5,6)])
print(g)

Graph with 6 nodes and 8 edges


In [6]:
simplicial = graph_to_neighbor_complex(g)
for ss in simplicial.simplices:
    print(ss)

frozenset({1})
frozenset({2})
frozenset({3})
frozenset({4})
frozenset({5})
frozenset({6})
frozenset({1, 2})
frozenset({1, 3})
frozenset({1, 4})
frozenset({2, 3})
frozenset({2, 4})
frozenset({3, 4})
frozenset({1, 5})
frozenset({2, 5})
frozenset({3, 5})
frozenset({4, 5})
frozenset({2, 6})
frozenset({5, 6})
frozenset({1, 2, 3})
frozenset({1, 2, 4})
frozenset({1, 3, 4})
frozenset({2, 3, 4})
frozenset({1, 2, 5})
frozenset({1, 3, 5})
frozenset({1, 4, 5})
frozenset({2, 3, 5})
frozenset({2, 4, 5})
frozenset({3, 4, 5})
frozenset({2, 5, 6})
frozenset({1, 2, 3, 4})
frozenset({1, 2, 3, 5})
frozenset({1, 2, 4, 5})
frozenset({1, 3, 4, 5})
frozenset({2, 3, 4, 5})
frozenset({1, 2, 3, 4, 5})


In [7]:
print(simplicial.up_laplacian_matrix(0).toarray())

[[ 4. -1. -1. -1. -1.  0.]
 [-1.  5. -1. -1. -1. -1.]
 [-1. -1.  4. -1. -1.  0.]
 [-1. -1. -1.  4. -1.  0.]
 [-1. -1. -1. -1.  5. -1.]
 [ 0. -1.  0.  0. -1.  2.]]


In [8]:
import torch_geometric
import torch

In [9]:
from itertools import combinations

In [11]:
data = torch_geometric.data.Data()
data.x = torch.zeros([6,1])
data.edge_index = torch.tensor([[0,0,0,1,1,1,2,4],[1,2,3,2,3,4,3,5]])

In [22]:
lift = SimplicialNeighborhoodLifting()

lifted_data = lift(data)

In [23]:
print(lifted_data)


Data(x=[6, 1], edge_index=[2, 8], incidence_1=[6, 12], laplacian_down_1=[6, 6], laplacian_up_1=[12, 12], incidence_2=[12, 11], laplacian_down_2=[12, 12], laplacian_up_2=[11, 11])


In [51]:
lift2 = CellCyclesLifting()

lifted_data = lift2(data)

In [52]:
print(lifted_data)

Data(x=[4, 1], edge_index=[2, 4], incidence_1=[4, 4], incidence_2=[4, 1], laplacian_up_1=[4, 4], laplacian_up_2=[4, 4], laplacian_down_2=[1, 1], laplacian_down_1=[4, 4], x_1=[4, 1])


In [50]:
data = torch_geometric.data.Data()
data.x = torch.zeros([4,1])
data.edge_index = torch.tensor([[0,0,1,2],[1,3,2,3]])
lifted_data = lift2(data)
print(lifted_data)

Data(x=[4, 1], edge_index=[2, 4], incidence_1=[4, 4], incidence_2=[4, 1], laplacian_up_1=[4, 4], laplacian_up_2=[4, 4], laplacian_down_2=[1, 1], laplacian_down_1=[4, 4], x_1=[4, 1])
