In [ ]:
import numpy as np
import pandas as pd

In [ ]:

import pandas as pd
df = pd.read_csv('/home/lev/projects/TopoBenchmark/tutorials/NPHA-doctor-visits_2.csv')
y = df['Number of Doctors Visited']
df = df.drop('Number of Doctors Visited', axis=1)
# Assuming 'df' contains your data
# Select categorical columns
categorical_columns = df.columns  # Include all columns if they are categorical

# Convert the DataFrame to numpy for processing
data_numpy = df.to_numpy()

# Perform one-hot encoding using pandas get_dummies
df_one_hot = pd.get_dummies(df, columns=categorical_columns)

X =np.array(df_one_hot*1)
n_nodex, n_hyperedge = X.shape
nodes, edges =  np.where(X==1)
init_edge = nodes.max() + 1
edges += init_edge
edge_index = np.stack([nodes, edges])

# features = features = sp.csr_matrix(X, dtype=np.float32)
# labels = torch.LongTensor(y.astype(float))

Age  Phyiscal Health  Mental Health  Dental Health  Employment  \
0      2                4              3              3           3   
1      2                4              2              3           3   
2      2                3              2              3           3   
3      2                3              2              3           3   
4      2                3              3              3           3   
..   ...              ...            ...            ...         ...   
709    2                2              2              2           3   
710    2                2              2              2           2   
711    2                4              2              3           3   
712    2                3              1              3           3   
713    2                3              2              2           1   

     Stress Keeps Patient from Sleeping  \
0                                     0   
1                                     1   
2                                     0   
3                                     0   
4                                     1   
..                                  ...   
709                                   0   
710                                   1   
711                                   0   
712                                   1   
713                                   1   

     Medication Keeps Patient from Sleeping  Pain Keeps Patient from Sleeping  \
0                                         0                                 0   
1                                         0                                 0   
2                                         0                                 0   
3                                         0                                 0   
4                                         0                                 0   
..                                      ...                               ...   
709                                       0                                 0   
710                                       0                                 0   
711                                       0                                 0   
712                                       0                                 1   
713                                       0                                 1   

     Bathroom Needs Keeps Patient from Sleeping  \
0                                             0   
1                                             1   
2                                             0   
3                                             1   
4                                             0   
..                                          ...   
709                                           1   
710                                           0   
711                                           0   
712                                           1   
713                                           1   

     Uknown Keeps Patient from Sleeping  Trouble Sleeping  \
0                                     1                 2   
1                                     0                 3   
2                                     1                 3   
3                                     0                 3   
4                                     0                 2   
..                                  ...               ...   
709                                   0                 3   
710                                   1                 2   
711                                   0                 3   
712                                   1                 3   
713                                   0                 2   

     Prescription Sleep Medication  Race  Gender  
0                                3     1       2  
1                                3     1       1  
2                                3     4       1  
3                                3     4       2  
4                                3     1       2  
..        

In [78]:
a = np.unique(y, return_counts=True)[1]
a/a.sum()

array([0.18347339, 0.5210084 , 0.29551821])

array([[    0,     0,     0, ..., 16241, 16241, 16241],
       [16264, 16316, 16324, ..., 16267, 16288, 16327]], dtype=int32)

array([[  0,   0,   0, ..., 713, 713, 713],
       [714, 719, 724, ..., 755, 756, 761]])

In [18]:
edges_unordered = np.genfromtxt('/home/lev/projects/hypergraph_transformer/data/AllSet_all_raw_data/20newsW100/20newsW100.edges',
                                    dtype=np.int32)

In [21]:

idx_features_labels = np.genfromtxt('/home/lev/projects/hypergraph_transformer/data/AllSet_all_raw_data/20newsW100/20newsW100.content',
                                        dtype=np.dtype(str))
# features = np.array(idx_features_labels[:, 1:-1])
features = idx_features_labels[:, 1:-1]
#     labels = encode_onehot(idx_features_labels[:, -1])
labels = idx_features_labels[:, -1].astype(float)



# build graph
idx = np.array(idx_features_labels[:, 0], dtype=np.int32)
idx_map = {j: i for i, j in enumerate(idx)}

In [23]:
edges = np.array(list(map(idx_map.get, edges_unordered.flatten())),
                     dtype=np.int32).reshape(edges_unordered.shape)

In [37]:
idx = np.where(edges.flatten() != edges_unordered.flatten())[0]//2
edges[idx]

array([[  400, 16252],
       [  400, 16272],
       [  400, 16276],
       ...,
       [  398, 16329],
       [  399, 16302],
       [  399, 16315]], dtype=int32)

In [38]:
edges_unordered[idx]

array([[  100, 16252],
       [  100, 16272],
       [  100, 16276],
       ...,
       [10878, 16329],
       [10879, 16302],
       [10879, 16315]], dtype=int32)

In [41]:
edge_index = edges.T
edge_index[0].max() == edge_index[1].min() - 1

True

In [42]:
edge_index[0]

array([    0,     0,     0, ..., 16241, 16241, 16241], dtype=int32)

In [44]:
edge_index[1]

array([16264, 16316, 16324, ..., 16267, 16288, 16327], dtype=int32)

In [48]:
edges_unordered.T[0].max() < edges_unordered.T[1].min()


True

In [51]:
idx_features_labels[:, 0]

array(['0', '1', '2', ..., '16339', '16340', '16341'], dtype='<U5')